application: q-versace
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /stylesheets
  static_dir: stylesheets
- url: /js
  static_dir: js
- url: /bootstrap
  static_dir: bootstrap 
- url: /bootstrap-timepicker
  static_dir: bootstrap-timepicker
- url: /svg
  static_dir: svg
- url: /images
  static_dir: images

- url: .*
  script: _q.app

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: "latest"
